[package]
name = "gpui_media"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[features]
default = ["backend-gstreamer"]
backend-gstreamer = [
    "dep:gst",
    "dep:gst-app",
    "dep:gst-video",
    "dep:gst-allocators",
    "dep:core-foundation",
    "dep:core-video",
]
backend-decv = [
    "dep:decv-core",
    "dep:decv-h264",
    "dep:decv-mp4",
]

[dependencies]
async-channel.workspace = true
decv-core = { git = "https://github.com/cradiy/decv", rev = "f7b52a0fc5c975c869238cd9c446536890864abb", optional = true }
decv-h264 = { git = "https://github.com/cradiy/decv", rev = "f7b52a0fc5c975c869238cd9c446536890864abb", optional = true }
decv-mp4 = { git = "https://github.com/cradiy/decv", rev = "f7b52a0fc5c975c869238cd9c446536890864abb", optional = true }
gpui.workspace = true
gst = { package = "gstreamer", version = "0.25", optional = true }
gst-app = { package = "gstreamer-app", version = "0.25", features = ["v1_24"], optional = true }
gst-video = { package = "gstreamer-video", version = "0.25", features = ["v1_24"], optional = true }
log.workspace = true
url.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gst-allocators = { package = "gstreamer-allocators", version = "0.25", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { workspace = true, optional = true }
core-video = { workspace = true, optional = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
gpui_platform = { workspace = true, features = ["wayland", "x11", "font-kit"] }

[[example]]
name = "decv_play"
required-features = ["backend-decv"]

[lints]
workspace = true
